# Generated by Django 4.1 on 2022-08-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.IntegerField()),
                ('nro_cuenta', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('tipo_operacion', models.IntegerField()),
                ('hora', models.DateTimeField()),
            ],
        ),
    ]
