# Generated by Django 4.1 on 2022-08-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employedd_id', models.IntegerField()),
                ('employedd_name', models.TextField()),
                ('employedd_surname', models.TextField()),
                ('employedd_DNI', models.IntegerField()),
                ('branch_id', models.TextField()),
            ],
        ),
    ]
